### ISSUE TITLE
kubectl create -f files/manifests/skydns-rc.yml yields replicationControllers "kube-dns-v8" already exists

### ISSUE THREAD

**Issue by mbruzek** [mbruzek/layer-k8s#29]
The `kubectl create -f files/manifests/skydns-rc.yml` command appears to run more than once, and is not idempotent. It fails the second time.

The error is: `Error from server: error when creating "files/manifests/skydns-rc.yml": replicationControllers "kube-dns-v8" already exists`

More of the log is here:

```
 etcd:8: Downloading kubelet: wget -nv -O /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.1.7/bin/linux/amd64/kube
ctl
 2016-04-15 21:43:18 URL:https://storage.googleapis.com/kubernetes-release/release/v1.1.7/bin/linux/amd64/kubectl [22589648/22589648] -> "/
usr/local/bin/kubectl" [1]
etcd:8: Invoking reactive handler: reactive/k8s.py:118:launch_skydns
 Error from server: error when creating "files/manifests/skydns-rc.yml": replicationControllers "kube-dns-v8" already exists
 Traceback (most recent call last):
   File "/var/lib/juju/agents/unit-kube-four-0/charm/hooks/etcd-relation-joined", line 19, in <module>
     main()
   File "/usr/local/lib/python3.4/dist-packages/charms/reactive/__init__.py", line 73, in main
     bus.dispatch()
   File "/usr/local/lib/python3.4/dist-packages/charms/reactive/bus.py", line 421, in dispatch
     _invoke(other_handlers)
   File "/usr/local/lib/python3.4/dist-packages/charms/reactive/bus.py", line 404, in _invoke
     handler.invoke()
   File "/usr/local/lib/python3.4/dist-packages/charms/reactive/bus.py", line 280, in invoke
     self._action(*args)
   File "/var/lib/juju/agents/unit-kube-four-0/charm/reactive/k8s.py", line 128, in launch_skydns
     check_call(split(cmd))
   File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
     raise CalledProcessError(retcode, cmd)
 subprocess.CalledProcessError: Command '['kubectl', 'create', '-f', 'files/manifests/skydns-rc.yml']' returned non-zero exit status 1
 hook "etcd-relation-joined" failed: exit status 1
```

This error leads to other errors in the log file (copying them here in case we see them again, or they are not related):

```
 Removing kubernetes_kubelet_1
 b'Unable to remove filesystem for c07639a04ba2a0722ad0395f0c4a893d38ae572404e1203e54b7538bbf346f49: remove /var/lib/docker/containers/c076
39a04ba2a0722ad0395f0c4a893d38ae572404e1203e54b7538bbf346f49/shm: device or resource busy'
 Traceback (most recent call last):
   File "/var/lib/juju/agents/unit-kube-four-0/charm/hooks/etcd-relation-joined", line 19, in <module>
     main()
   File "/usr/local/lib/python3.4/dist-packages/charms/reactive/__init__.py", line 73, in main
     bus.dispatch()
   File "/usr/local/lib/python3.4/dist-packages/charms/reactive/bus.py", line 421, in dispatch
     _invoke(other_handlers)
   File "/usr/local/lib/python3.4/dist-packages/charms/reactive/bus.py", line 404, in _invoke
     handler.invoke()
   File "/usr/local/lib/python3.4/dist-packages/charms/reactive/bus.py", line 280, in invoke
     self._action(*args)
   File "/var/lib/juju/agents/unit-kube-four-0/charm/reactive/k8s.py", line 153, in master
     compose.up('kubelet')
   File "/usr/local/lib/python3.4/dist-packages/charms/docker/compose.py", line 133, in up
     run(cmd, self.workspace)
   File "/usr/local/lib/python3.4/dist-packages/charms/docker/runner.py", line 19, in run
     out = check_output(split(cmd))
   File "/usr/lib/python3.4/subprocess.py", line 620, in check_output
     raise CalledProcessError(retcode, process.args, output=output)
 subprocess.CalledProcessError: Command '['docker-compose', 'up', '-d', 'kubelet']' returned non-zero exit status 1
 hook "etcd-relation-joined" failed: exit status 1
``
```

**Comment by mbruzek** [comment]
I don't see that we call this command twice. Did kubernetes create it? We can either make the command not fail if it returns a non-zero error code, or use states to prevent from running this twice.

**Comment by lazypower** [comment]
This was refactored a while ago @mbruzek - do you know if this is still an issue?

**Comment by mbruzek** [comment]
@chuckbutler I haven't seen it in the latest refactored code. I created the bug to track if we needed a guard for the DNS creation. If it hasn't been a problem I am fine to close it for now.
